# Generated by Django 5.1 on 2024-11-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('tela', models.CharField(max_length=50)),
                ('talla', models.IntegerField()),
                ('precio', models.FloatField()),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
    ]
