# Generated by Django 5.1 on 2024-11-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('id_libro', models.PositiveBigIntegerField()),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.FloatField()),
                ('id_cliente', models.PositiveSmallIntegerField()),
                ('id_empleado', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
