# Generated by Django 5.1 on 2024-12-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='id_libro',
            new_name='id_producto',
        ),
    ]
