# Generated by Django 5.1 on 2024-12-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='edad',
            field=models.DateField(),
        ),
    ]
