# Generated by Django 5.1 on 2024-11-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.PositiveBigIntegerField()),
                ('salario', models.FloatField()),
                ('edad', models.PositiveBigIntegerField()),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
    ]
