# Generated by Django 5.1 on 2024-12-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado_app', '0002_alter_empleados_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='edad',
            new_name='dateedad',
        ),
    ]
