# Generated by Django 5.1 on 2024-12-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado_app', '0003_rename_edad_empleados_dateedad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='dateedad',
            new_name='edad',
        ),
    ]
