# Generated by Django 5.1 on 2024-11-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('txtdireccion', models.CharField(max_length=50)),
                ('numtelefono', models.CharField(max_length=50)),
                ('txtcorreo', models.CharField(max_length=50)),
                ('numstock', models.PositiveIntegerField()),
                ('numempleados', models.PositiveIntegerField()),
                ('txthorario', models.CharField(max_length=50)),
            ],
        ),
    ]
