# Generated by Django 5.1 on 2024-11-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id_distribuidor', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('costo', models.TextField(max_length=10)),
                ('numentregas', models.PositiveIntegerField()),
                ('telefono', models.TextField(max_length=12)),
                ('correo', models.EmailField(max_length=254)),
                ('nombre', models.TextField(max_length=60)),
                ('ciudad', models.TextField(max_length=50)),
            ],
        ),
    ]
